In [77]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [78]:
# getting data set
df = pd.read_csv("mushrooms.csv")
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring    8124 non-null   object
 15  stalk-color-below-ring    8124 non-null   object
 16  veil-type                 8124 non-null   object
 17  veil-color                8124 non-null   object
 18  ring-number               8124 non-null   object
 19  ring-type                 8124 non-null   object
 20  spore-print-color         8124 non-null   object
 21  population                8124 non-null   object
 22  habitat                   8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

In [80]:
le = LabelEncoder()

In [81]:
df_encoded = df.apply(le.fit_transform, axis =0)
df_encoded.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1

In [82]:
df = df_encoded.values

In [83]:
x = df[:, 1: ]
y = df[:, 0]
x,y

(array([[5, 2, 4, ..., 2, 3, 5],
        [5, 2, 9, ..., 3, 2, 1],
        [0, 2, 8, ..., 3, 2, 3],
        ...,
        [2, 2, 4, ..., 0, 1, 2],
        [3, 3, 4, ..., 7, 4, 2],
        [5, 2, 4, ..., 4, 1, 2]], shape=(8124, 22)),
 array([1, 0, 0, ..., 0, 1, 0], shape=(8124,)))

In [84]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [85]:
print(x_train.shape)
print(x_test.shape)

(6499, 22)
(1625, 22)

# Posterior Propability

##Likelyhood

##Prior Propab

In [86]:
def prior_propab(y_train, label):

    m = y_train.shape[0]
    s = np.sum(y_train == label)

    return s/m

In [87]:
def cond_propab(x_train, y_train, feature_col, feature_val, label):

    x_filtered = x_train[y_train == label]

    num = np.sum(x_filtered[:, feature_col] == feature_val)

    demon = x_filtered.shape[0]

    return float(num/demon)

In [88]:
def predict(x_train, y_train, x_sample):

    n_features = x_train.shape[1]

    labels = np.unique(y_train)

    posteriors = []

    for label in labels:

        likelihood = 1.0

        for fea in range(n_features):

            cond = cond_propab(x_train, y_train, fea, x_sample[fea], label)

            likelihood *= cond

        prior = prior_propab(y_train, label)

        posterior = likelihood * prior

        posteriors.append(posterior)

    return labels[np.argmax(posteriors)]

In [89]:
def accuracy(x_train, y_train, x_test, y_test):

    pred = []

    for i in range(x_test.shape[0]):

        p = predict(x_train, y_train, x_test[i])

        pred.append(p)

    y_pred = np.array(pred)

    acc = np.sum(y_pred == y_test) / y_test.shape[0]

    return acc

In [92]:
accuracy(x_train, y_train, x_test, y_test)*100

np.float64(99.63076923076923)